name: ARM Support Check

permissions:
  issues: write  # Permission to comment on and update issues

on:
  issues:
    types:
      - opened
      - edited
      - reopened  # Triggered on opening, editing, or reopening issues

jobs:
  check_arm_support:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the issue mentions ARM support
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;

            if (!issue) {
              core.setFailed("This workflow can only be triggered by issue events.");
              return;
            }

            const issueBody = issue.body || "";

            const armKeywords = [
              "arm",
              "arm64",
              "arm32",
              "aarch64",
              "android",
              "termux"
            ];

            const message = "If the software does not run on ARM architectures, please follow the compilation instructions in the README.md to compile the software for it.";

            // Check if ARM or arm64 is mentioned in the issue body
            const containsArm = armKeywords.some(keyword => issueBody.toLowerCase().includes(keyword));

            if (containsArm) {
              // Comment on the issue if ARM support is mentioned
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: message,
              });
            }
