name: Build and Upload Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-upload-linux:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install build essentials for Linux
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Step 3: Compile the main.cpp file
      - name: Build main.cpp
        run: |
          g++ -o main main.cpp

      # Step 4: Upload the compiled binary as an artifact
      - name: Upload binary to tag
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./main
          asset_name: main-linux
          asset_content_type: application/octet-stream

  build-and-upload-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install MSVC build tools
      - name: Install MSVC tools
        run: |
          # MSVC compiler is pre-installed on windows-latest runner, no additional setup required.

      # Step 3: Compile the main.cpp file
      - name: Build main.cpp
        run: |
          cl.exe /EHsc /Fe:main.exe main.cpp

      # Step 4: Upload the compiled binary as an artifact
      - name: Upload binary to tag
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./main.exe
          asset_name: main-windows.exe
          asset_content_type: application/octet-stream
