name: Close Non-compliant issues

permissions:
  issues: write

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  close_non_compliant_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the issue follows the template
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;

            if (!issue) {
              core.setFailed("This workflow can only be triggered by issue events.");
              return;
            }

            const issueBody = issue.body || "";

            const templateKeywords = [
              "**Describe the bug**",
              "**Is your feature request related to a problem? Please describe.**",
              "**Describe the vulnerability**"
            ];

            const isCompliant = templateKeywords.some(keyword => issueBody.includes(keyword));

            if (!isCompliant) {
              // Close the issue if it's not compliant
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: "closed",
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: "This issue does not follow a template and has therefore been closed. Please see [CONTRIBUTING.md.](https://github.com/benja2998/multitoolplusplus/blob/main/CONTRIBUTING.md)"
              });
            }
